# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				allay = true
				llama = true
				bat = true
				frog = true
				husk = true
				hoglin = true
				camel = true
				firework_rocket = true
				armor_stand = true
				giant = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				goat = true
				furnace_minecart = true
				item_frame = true
				horse = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				chicken = true
				donkey = true
				evoker_fangs = true
				fox = true
				chest_minecart = true
				iron_golem = true
				area_effect_cloud = true
				blaze = true
				end_crystal = true
				endermite = true
				cat = true
				guardian = true
				ghast = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				elder_guardian = true
				chest_boat = true
				boat = true
				hopper_minecart = true
				falling_block = true
				cave_spider = true
				cod = true
				command_block_minecart = true

